version: "3.9"
services:
  devopsdb:
    image: nikhilkotharu/dockerapp:db
    ports:
      - "4567:3306"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: '128m'
        reservations:
          cpus: '0.5'
          memory: '100m'
    networks:
      - mynetwork
    volumes:
      - db_volume:/opt/nikhil

  application:
    image: nikhilkotharu/dockerapp:web
    ports:
      - "6666:8080"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: '128m'
        reservations:
          cpus: '0.5'
          memory: '100m'
    depends_on:
      - devopsdb
    networks:
      - mynetwork
    volumes:
      - app_volume:/opt/nikhil

networks:
  mynetwork:
    driver: overlay

volumes:
  db_volume:
  app_volume:
