version: "3.9"
services:
  devopsdb:
    image: nikhilkotharu/dockerapp:db
    ports:
      - "4569:3306"
    deploy:
      replicas: 3
    networks:
      - mynetwork
    volumes:
      - db_volume:/opt/nikhil

  application:
    image: nikhilkotharu/dockerapp:web
    ports:
      - "5159:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork
    volumes:
      - app_volume:/opt/nikhil

networks:
  mynetwork:
    driver: overlay

volumes:
  db_volume:
  app_volume:
